### ISSUE TITLE
Parenthesized identifiers in expressions not being parsed

### ISSUE THREAD

**Issue by jpathy** [quintenkasteel/language-javascript#103]
````
 function foo() {
 var x, y;
 x += (y);
}
````
Above program fails to parse. I looked at the grammar file but i am not sure why it's not being parsed as `JSExpressionParen`.

**Comment by jpathy** [comment]
The issue is not present in latest new-ast(that i tested), but it is there in 0.6.13.

**Comment by rhendric** [comment]
It makes sense that b2f4cfa would have fixed this. That commit resolved a grammar ambiguity between `(y)` as an expression and `(y)` as the parameter list of an arrow function, which must have been resolving in favor of the latter. (The issue presumably didn't come up that much, since it's rare to parenthesize a single variable like that, and only plain identifiers were supported as parameters prior to that commit.)

**Comment by erikd** [comment]
Should I do a new release?

**Comment by erikd** [comment]
Version 0.6.1.4 is now on Hackage.
