### ISSUE TITLE
strings with backticks are misrecognized as template literals

### ISSUE THREAD

**Issue by jpathy** [quintenkasteel/language-javascript#104]
````
function foo() {
  a = '`sadsd`';
}
function bar() {
  a = '`sadas`';
}
````
Above program fails to parse.

**Comment by rhendric** [comment]
My bug! I'm looking into it.

**Comment by jpathy** [comment]
For the above program the following rule goes wrong:
https://github.com/erikd/language-javascript/blob/b2f4cfab063295f9b27a0bbb02143d03863c167c/src/Language/JavaScript/Parser/Lexer.x#L260

I looked into the spec a bit and it seems that we need more lexical start codes than just `reg`, `divide`, see : https://www.ecma-international.org/ecma-262/7.0/#sec-ecmascript-language-lexical-grammar .

**Comment by rhendric** [comment]
Yeah, I came to the same conclusion. Unfortunately, I think we also need more state shared between the parser and the lexer, because the lexer alone can't determine whether a given `}` is the delimiter between expression and template characters. I have a work in progress fix; I'm just in the process of polishing it up now.
